/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HumanTransformRouteImport } from './routes/human-transform'
import { Route as BusinessVenturesRouteImport } from './routes/business-ventures'
import { Route as IndexRouteImport } from './routes/index'

const HumanTransformRoute = HumanTransformRouteImport.update({
  id: '/human-transform',
  path: '/human-transform',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessVenturesRoute = BusinessVenturesRouteImport.update({
  id: '/business-ventures',
  path: '/business-ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-ventures': typeof BusinessVenturesRoute
  '/human-transform': typeof HumanTransformRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-ventures': typeof BusinessVenturesRoute
  '/human-transform': typeof HumanTransformRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-ventures': typeof BusinessVenturesRoute
  '/human-transform': typeof HumanTransformRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/business-ventures' | '/human-transform'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/business-ventures' | '/human-transform'
  id: '__root__' | '/' | '/business-ventures' | '/human-transform'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessVenturesRoute: typeof BusinessVenturesRoute
  HumanTransformRoute: typeof HumanTransformRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/human-transform': {
      id: '/human-transform'
      path: '/human-transform'
      fullPath: '/human-transform'
      preLoaderRoute: typeof HumanTransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-ventures': {
      id: '/business-ventures'
      path: '/business-ventures'
      fullPath: '/business-ventures'
      preLoaderRoute: typeof BusinessVenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessVenturesRoute: BusinessVenturesRoute,
  HumanTransformRoute: HumanTransformRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
