/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VenturesRouteImport } from './routes/ventures'
import { Route as HumanTransformRouteImport } from './routes/human-transform'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessVenturesRouteImport } from './routes/business-ventures'
import { Route as IndexRouteImport } from './routes/index'

const VenturesRoute = VenturesRouteImport.update({
  id: '/ventures',
  path: '/ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanTransformRoute = HumanTransformRouteImport.update({
  id: '/human-transform',
  path: '/human-transform',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessVenturesRoute = BusinessVenturesRouteImport.update({
  id: '/business-ventures',
  path: '/business-ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-ventures': typeof BusinessVenturesRoute
  '/contact': typeof ContactRoute
  '/human-transform': typeof HumanTransformRoute
  '/ventures': typeof VenturesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-ventures': typeof BusinessVenturesRoute
  '/contact': typeof ContactRoute
  '/human-transform': typeof HumanTransformRoute
  '/ventures': typeof VenturesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-ventures': typeof BusinessVenturesRoute
  '/contact': typeof ContactRoute
  '/human-transform': typeof HumanTransformRoute
  '/ventures': typeof VenturesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-ventures'
    | '/contact'
    | '/human-transform'
    | '/ventures'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/business-ventures' | '/contact' | '/human-transform' | '/ventures'
  id:
    | '__root__'
    | '/'
    | '/business-ventures'
    | '/contact'
    | '/human-transform'
    | '/ventures'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessVenturesRoute: typeof BusinessVenturesRoute
  ContactRoute: typeof ContactRoute
  HumanTransformRoute: typeof HumanTransformRoute
  VenturesRoute: typeof VenturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventures': {
      id: '/ventures'
      path: '/ventures'
      fullPath: '/ventures'
      preLoaderRoute: typeof VenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-transform': {
      id: '/human-transform'
      path: '/human-transform'
      fullPath: '/human-transform'
      preLoaderRoute: typeof HumanTransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-ventures': {
      id: '/business-ventures'
      path: '/business-ventures'
      fullPath: '/business-ventures'
      preLoaderRoute: typeof BusinessVenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessVenturesRoute: BusinessVenturesRoute,
  ContactRoute: ContactRoute,
  HumanTransformRoute: HumanTransformRoute,
  VenturesRoute: VenturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
